name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: macos-latest
          - os: windows-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: setup python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: setup node
      uses: actions/setup-node@v3
      with:
        node-version: 14
      
    - name: install yarn
      run: npm install --global yarn
        
    - name: install requirements
      run: npm install

    - name: build
      run: yarn package
      
    - name: upload
      uses: actions/upload-artifact@v2
      with:
        name: release
        path: ./release/FribbelsE7Optimizer*
